### ISSUE TITLE
Containerize Codenvy Infrastructure

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1032]
Epic to productize the containerization of Codenvy. This includes the movement of the "hackathon" branch into master, the view of all code changes, and improvements to the configuration and CLI.

-- P1
- [x] @garagatyi  - Firewall issues - not able to install on certain linux os. Socat connection is seen as external. Good idea to have two IPs for a swarm node (internal IP & external IP). Going to internal IP helps previewURL.  This is a code-level change. Nothing hard - just need to find a solution.  Error was "no healthy swarm node in a cluster".  #1053
- [x] @riuvshin - Does not work with real DNS names.
- [x] Dmytro - Licensing [improvements and changes](https://github.com/codenvy/enterprise/issues/13)
- [x] @benoitf Eclipse Che CLI Refactoring + Improvements https://github.com/eclipse/che/issues/2977
- [x] @TylerJewell  + Sergii Kab - Add "upgrade" command to the CLI #1033
- [x] @JamesDrummond  - Update hackathon docs. https://github.com/codenvy/codenvy/blob/hackathon/DOCS.md 
- [x] @TylerJewell  - Update docs to remove listing of environment variables https://github.com/codenvy/codenvy/blob/hackathon/DOCS.md
- [x] @garagatyi  - Merge hackathon branch into master #1069 
- [x] @garagatyi  - Make networking configuration between bridge vs. overlay configurable #1078 
- [x] @eivantsov  - 'codenvy destroy' is failing on some linux boxes #1029  
- [x] @riuvshin - development mode on linux work wrong, cli restart work incorrect https://github.com/codenvy/codenvy/issues/1070
- [x] @mkuznyetsov   - Codenvy in Docker: Fail to start a workspace on Windows https://github.com/codenvy/codenvy/issues/1093
- [x] @TylerJewell @riuvshin  Workspace agents are not stopped during codenvy stop or restart https://github.com/codenvy/codenvy/issues/1226
- [x] @riuvshin Workspace delete fail https://github.com/codenvy/codenvy/issues/1227
- [x] @garagatyi  custom stacks does not work https://github.com/codenvy/codenvy/issues/1271
- [x] figure out how to update users codenvy.env che.env files https://github.com/codenvy/codenvy/issues/1278

-- P2
- [ ] @mkuznyetsov Only user with role 'manageSystem' should be able to call NodeService methods https://github.com/codenvy/codenvy/issues/1292
- [x] make it possible to use custom codenvy images like customer-saas https://github.com/codenvy/codenvy/issues/1162
- [x] Distribute agents from separate container, not from API #1153 
- [x] @dzamosenchuk @skryzhny set-up nightly5 like env for codenvy in docker https://github.com/codenvy/infrastructure/issues/12
- [ ] @skabashnyuk Dockerized Codenvy Test Scenarios https://github.com/codenvy/codenvy/issues/1256
- [x] @garagatyi  - Test behaviors of workspace performance if rsync agent fails #1079 
- [x] @riuvshin - Real life data for codenvy/version #1083 
- [x] @riuvshin - CLI not always detecting valid assembly #1030 
- [x] @eivantsov  - Implement backup of named volume for windows, to get database data #1080
- [x] @riuvshin - crossplatform backup / restore commands #1067  
- [x] @garagatyi  - CLI logs are be rewritten on each run #1081
- [x] @riuvshin - Move private Docker registry configuration to files #1027 
- [x] @riuvshin - all docker image names and versions must be used from `images` manifests for particular version https://github.com/codenvy/codenvy/issues/1156

-- P3
- [x] @mkuznyetsov cannot use codenvy.sh via symlink https://github.com/codenvy/codenvy/issues/1118
- [x] Anna - Remove unnecessary screens from Admin dashboard #1091
- [x] Eugene - Test and doculent usage of codenvy in container using docker-machine to launch additional swarm nodes #1176
- [x] Eugene - Document the monitoring configuration on the docs page
- [x] Eugene+Roman make and use tags for any container
- [x] @riuvshin Make HTTP/S on - off configuration simpler
- [ ] Add unit tests for CLI, Puppet, etc
- [x] Create & run QA tests
- [ ] Develop and run performance tests on Codenvy in container codenvy/infrastructure#12
- [ ] Create procedure for customers to migrate from puppet-based install to docker-based install
- [x] @riuvshin Allow to suspend API server start in development mode #1151 
- [ ] Terminal and WS agents are mounted as empty folders in codenvy in container mode #1149

**Comment by TylerJewell** [comment]
Closing this epic as it was turning into more of a running list of tasks.  And all of the important tasks have been documented and scheduled elsewhere.  Good work on this project everyone.
