### ISSUE TITLE
5.0.0-M7 Milestone Plan

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1055]
## Milestone Overview
- Bug fixes and cleanup
- NOTE: This release includes changes from Eclipse Che [TBD milestone 5.0.0-M7]().

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M7 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M6 to 5.0.0-M7.**

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**
#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Issues
- [x]  Can not create a workspace snapshot kind/bug kind/docs severity/blocker #1114  
- [x]  Wrong behavior when initialize git repository (regression) kind/bug  #1094  
- [x]  Cannot configure a project after consuming factoty (regression) kind/bugseverity/blocker   #1092  
- [x]  Development mode on linux work wrong, cli restart work incorrect kind/task #1070  
- [x]  Crossplatform backup / restore commands kind/task  #1067  
- [x]  Constantly re-reading project structure kind/bug severity/blocker  #1037  
- [x]  Codenvy start in container doesn't work if development mode is on and codenvy.sh is called from outside of codenvy repo kind/bug  #1030  
- [x]  Change way how we configure docker registries kind/task  #1027  
- [x]  CODENVY-602 Avoid NPE when ending sessions of stopped workspaces  #1026  
- [x]  Clarify messages in UD for snapshotting kind/enhancement  #936   
- [x]  Remove extra workspace running notification. kind/enhancement  #934   
- [x]  Stopped IDE should provide clear state and options to the user kind/enhancement #932   
- [x]  CHE-2015 Rename configuration properties  #902   
- [x]  The toast loader is not showed when workspace is stopped (regression) kind/bug #901
- [x]  Codenvy on-prem bootstrap scripts fails when proxy URL has trailing slash at the end kind/bug  #886   
- [x]  Describe and test SASL configuration of LDAP connection kind/task  #813   
- [x]  SSH key never gets injected into workspace machine kind/bug #804      
- [x] codenvy/plugin-openshift Investigate the reasons of add service error kind/bug  [#41  ](https://github.com/codenvy/plugin-openshift/issues/41)

## Migration Considerations

In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M7 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M6 to 5.0.0-M7.
