### ISSUE TITLE
Alex's must have issues for Checonf

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1088]
- [x] Alex - Merge hackathon branch into master #1069 
- [x] Alex - Test behaviors of workspace performance if rsync agent fails #1079 
- [x] Roman - crossplatform backup / restore commands #1067  
- [x] Codenvy in Docker: Fail to start a workspace on Windows #1093

**Comment by bmicklea** [comment]
@skabashnyuk Tyler also mentioned two nice to haves (in order of priority):
- [ ] Dmytro - Change licensing behavior https://github.com/codenvy/enterprise/issues/13
- [ ] Anna - Remove unnecessary screens from Admin dashboard #1091

**Comment by bmicklea** [comment]
@ashumilova note that we added an item for you regarding removal of unnecessary sections of the Admin dashboard.

**Comment by skabashnyuk** [comment]
@bmicklea I would like to narrow the scope of this issue to Docker(aka Alexe's) specific issues of Codenvy CLI.

**Comment by ashumilova** [comment]
@bmicklea we completely remove them in main branch, right?

**Comment by benoitf** [comment]
> Remove unnecessary screens from Admin dashboard #1091

is overlapping with https://github.com/codenvy/codenvy/issues/1032 P3 item :

`Florent remove part on UD for admins where we were able to change configs with IM server. we don't have IM server anymore`

**Comment by bmicklea** [comment]
@skabashnyuk if there is an epic for CheConf items already then I can move those items there. If not then this seems like it should be the CheConf epic and we should put all tasks here so they're centralized. I don't want to risk something getting missed.

**Comment by garagatyi** [comment]
Fixed
