### ISSUE TITLE
Codenvy workspace snapshotting reliability

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1171]
Since snapshotting is very resource intensive operation we need to make sure that system is able to handle big traffic.

- [x] Avoid of concurrent snapshots on same node. https://github.com/codenvy/codenvy/issues/1127 
- [x] Workspace is not deleted after finishing selenium test   https://github.com/codenvy/codenvy/issues/593
- [x] Performance testing of workspace snapshotting opperation https://github.com/codenvy/codenvy/issues/1174
