### ISSUE TITLE
Dockerized Codenvy Test Scenarios

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#1256]
Some enterprise testing scenarios that we need to verify:
- [x] @skabashnyuk Testing of  work behind http proxy https://github.com/codenvy/codenvy/issues/1275

- [x] @TylerJewell  Extend the Che CLI with http proxy parameters https://github.com/eclipse/che/issues/3259

- [x] @benoitf @skabashnyuk   Perform the same proxy tests for Che as well.

- [x] @skryzhny @skabashnyuk Setup a firewall scenario  https://github.com/codenvy/infrastructure/issues/27
- [x]  @skabashnyuk Script to simulate adding / removing additional nodes 
https://github.com/codenvy/codenvy/issues/1176
- [x] @riuvshin  Add in a CI job to generate the offline docker images required for Che and Codenvy when we tag a version.  Today a user must run codenvy/cli offline to generate these files, but we will want these files in a single location that is part of our releases as well.  This is necessary because eventually we will create ZIP / TAR / EXE packages that install and run codenvy offline.

- [x] @benoitf  is planning to add "codenvy ssh", "codenvy sync", and other utilities as first class citizens into the CLI.  We need to test all of these functions that they work the same way on Che and Codenvy, and that the supporting docs properly outline how they are to be used.  We have docs for these utilities on the che site, but we need them to be added into the new Che / Codenvy docs.  If the engineers can verify usage and also keep a record of the output of the test cases + syntax used to test, then Tyler can update the docs to be consistent.

URLs of proxy in the Che office for testing proporse:
http://proxy.ua.codenvy-dev.com:3128/ - without authentication.
http://testuser:testpassword@proxy.ua.codenvy-dev.com:3129/ - with authentication.

**Comment by skabashnyuk** [comment]
>Creates scripts that use docker-machine to simulate adding / removing additional nodes.
@TylerJewell  what does it mean ```simulate adding / removing ``` - helps add existed real node or what?

**Comment by TylerJewell** [comment]
Imagine you are on a laptop and you want to test Codenvy with multiple nodes. You need a way to launch a VM with a 2nd or 3rd node.  docker-machine would be the utility that lets you do this.  And then once you have that 2nd node, you can use "codenvy add-node" syntax to test that it works.

**Comment by skabashnyuk** [comment]
>@benoitf is planning to add "codenvy ssh", "codenvy mount", and other utilities as first class >citizens into the CLI. We need to test all of these functions
We need test plan  to do that.
