### ISSUE TITLE
5.0.0-M8 Milestone Plan

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1329]
## Milestone Overview
- Bug fixes and cleanup
- Cleanup admin dashboard.
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M8](https://github.com/eclipse/che/issues/3094).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M8 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M7 to 5.0.0-M8.**

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **Target: November 9, 2016**
- GitHub release complete (QA verified) milestone: **Target: November 11, 2016**
#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Issues
- [x] Not all editor tabs are closed after stopping workspace (regression) kind/bug #1270  
- [x] Puppet should set Password Expires for the `codenvy` user to `never` explicitly kind/enhancement   #1241  
- [x] Codenvy in Docker: Workspace delete fail kind/bug    #1227  
- [x] Performance testing of workspace snapshotting opperation kind/task   #1174  
- [x] "Installation Manager server error" in Admin Dashboard kind/bug  #1168  
- [x] DockerConnector exception "Could not kill running container" kind/bug severity/blocker   #1164  
- [x] MachineBackupManager Process failed. Exit code 255 kind/bug severity/blocker   #1163  
- [x] All docker image names and versions must be used from images manifests for particular version kind/task  #1156  
- [x] Running process is not terminated after closing in the console kind/bug severity/blocker  #1145  
- [x] Avoid of concurrent snapshots on same node. kind/enhancement   #1127  
- [x] Remove unnecessary screens from Admin dashboard kind/enhancement  #1091  
- [x] Manage empty states in IDE kind/enhancement  #1086  
- [x] Proxy configuration broke link on ws-agent API  #1076  
- [x] Viewing HTML Files kind/bug severity/blocker #1060  
- [x] System errors page styling update kind/task  #1052  
- [x] Maintenance page's styling update kind/task  #1051  

## Migration Considerations

In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M8 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M7 to 5.0.0-M8.
