### ISSUE TITLE
5.0.0 Milestone Overview

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1528]
## Milestone Overview
- Bug fixes and cleanup
- Cleanup admin dashboard.
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0](https://github.com/eclipse/che/issues/3093).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M8/M9 to 5.0.0.**

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be a development release available on GitHub only.

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Issues
- [x] update release automation kind/task    #1472  
- [x] Fix package/deploy issue of docs. kind/task #1442  
- [x] Change access to docs from dashboard #1432  
- [x] dev mode not consistent kind/bug severity/blocker  #1431  
- [x] Create new docs repos kind/docs #1416  
- [x] Workspace start occasionally fails if docker image doesn't contain ssh and rsync kind/bugseverity/blocker   #1392  
- [x] Add ZooKeeper key-value container to the Dockerized Codenvy start(). kind/task  #1388  
- [x] add docs for new LIMIT props kind/docs #1385  
- [x] Clarify Codenvy configuration for using private docker registries kind/docs   #1378  
- [x] Generating docs with Maven is broken kind/bug severity/blocker  #1376  
- [x] upgrade docker registry to 2.5.1 kind/task  #1375  
- [x] Replace LOG.error with LOG.debug kind/task   #1358  
- [x] Dockerized Install Behind Proxy - Workspaces Do Not Start kind/bug severity/blocker  #1351  
- [x] Improve homepage flow for docs site kind/docs  #1349  
- [x] Improve How CLI Gets List of Stack Images kind/enhancement   #1343  
- [x] Run Dockerized Codenvy in a Vagrant VM kind/bug kind/task severity/blocker #1342  
- [x] Port Che CLI for Codenvy SaaS kind/enhancement #1340  
- [x] Logs of workspace containers and agents are not shown when WS starts in IDE (regression)kind/bug severity/blocker  #1337  
- [x] Restart workspace from IDE ends up with an error (regression) kind/bug  #1335  
- [x] Error Sync port is not exposed in ws-machine kind/bug severity/blocker  #1333  
- [x] Create update script that will transform absolute to relative links for script for the same host.kind/task    #1324  
- [x] Codenvy CLI commands: list-nodes and remove-node are not working kind/bug #1322  
- [x] update docker to latest available for puppet based codenvy kind/task  #1301  
- [x] Codenvy in container doesn't check availability of port 8000 in development mode kind/bug #1282  
- [x] Add to exception information about on which node it occured kind/task  #1279  
- [x] Add menus item to embed docs into the product kind/enhancement  #1274  
- [x] Display version number and Codenvy logo in dashboard's footer kind/enhancement  #1273  
- [x] All bitnami stacks do not work on the nightly server kind/bug severity/blocker  #1271  
- [x] "Reading Project Structure" pop-up kind/bug severity/blocker    #1249  
- [x] Strange warning about the age of cli kind/bug #1235  
- [x] Rename License in wsmaster/codenvy-hosted-api-license to SystemLicense kind/task  #1223  
- [x] Add support for BitBucket Server to Codenvy integrations kind/enhancement  #1178  
- [x] Test and document usage of codenvy in container using docker-machine to launch additional swarm nodes kind/task #1176  
- [x] DockerConnector exception "Could not kill running container" kind/bug severity/blocker  #1164  
- [x] make it possible to use custom codenvy images like for codenvy saas kind/enhancement #1162  
- [x] Create 'Access Requires Fair Source Licence Acceptance' page in site project kind/enhancementseverity/blocker  #1154  
- [x] Distribute agents from separate container, not from API kind/task  #1153  
- [x] Bugs in Profile Preference dialog kind/bug  #1106  
- [x] Workspaces fail to start in cases where certain firewalls are active kind/enhancement   #1053  
- [x] Maintenance page's styling update kind/task   #1051  
- [x] Ws-agent produces an enormous amount of logs when unable to resolve hostname of masterkind/bug  #959   

## Migration Considerations

In order to upgrade and migrate an existing Codenvy install to this version 5.0.0 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M8/M9 to 5.0.0.
