### ISSUE TITLE
Productizing Team Capabilities Phase1

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#1549]
# Definition
Team capabilities (Defined in issue: https://github.com/codenvy/codenvy/issues/916) have been in progress since few sprints and we are reaching a state where we envision to merge and deliver to users those capabilities.
In the objective of shipping the Team Capabilities Phase1, we have various productization tasks to complete. Those tasks are covering all areas to deliver great set of features to end-user, from writing automated tests, to documentation and release note items.

We will use this issue as an umbrella issue in order to help identify, classify and prioritize the various productization tasks.

We will also use this issue to collect all feedbacks and collectively decide how to handle them.

## Preliminary Steps
- [x] Provide acceptance server with daily update on Teams Capabilities https://github.com/codenvy/infrastructure/issues/56
- [x] Email everyone for open tested
- [x] Setup daily stand-up with team/PM to review and keep this issue up-to-date

## Documentation
In this section, we list all the sub-tasks that are related to documentation either at end-user or api level.
- [x] Permission API - Swagger documentation https://github.com/codenvy/codenvy/issues/1546
- [x] Permission API - End user documentation https://github.com/codenvy/codenvy-docs/issues/41
- [x] Organization API - Swagger documentation https://github.com/codenvy/codenvy/issues/1547
- [x] Team End user documentation https://github.com/codenvy/codenvy-docs/issues/42
- [x] Billing and CC - End user documentation https://github.com/codenvy/codenvy-docs/issues/43
- [x] Tutorial - How to create a team ?

## Tests 
In this section, we list all the sub-tasks that are related to tests.
- [x] Define list of user stories to test
- [x] Automated tests for critical user stories
- [x] Run test on all user stories by team
- [x] Stress test session by team
- [ ] QA test cycle

## Product
This section list all the sub-tasks needed from product to deliver enjoyable features for end-user and efficient features from company. 
- [x] List and review all messages displayed to end-users https://github.com/codenvy/codenvy/issues/1548
- [x] Define feature metrics criteria
- [ ] Provide solution (automated or not) to measure the metrics

## Release Note
In this section, we list the task that are needed for the release note purpose.
- [x] Explain our vision for Teams
- [x] Describe how to create a first team
- [x] Add animated gif for creating a team
- [x] Explain ressources management
- [x] Snapshot showing resources usage (on dashboard)
- [x] Explain billing model
- [x] Show how to handle billing info and CC 

## Marketing Website
- [x] Update product overview page explaining value of team
- [x] Update pricing page outlining pricing for teams and RAM
- [x] Check if pricing FAQ needs additional questions

## Bugs
In this section, we list all the known bugs that are needed before shipping the feature.
**To be fixed asap - Critical** 
- [x] Display RAM widget on dashboard - https://github.com/codenvy/saas/issues/174
- [x] Fix typo in workspace details "Get idle timeout..." - https://github.com/codenvy/saas/issues/176
- [x] Fix formatting issue in docs for subscription, teams and permissions - https://github.com/codenvy/docs/issues/91

**To be fixed before shipping - P1**
- [x] Wrong allowed characters in billing screen - https://github.com/codenvy/saas/issues/153
- [x] Inconsistent RAM values between CAP and workspace's ram configuration - https://github.com/codenvy/saas/issues/152
- [x] Inconsistent RAM unit between subscriptions and workspace's ram configuration - https://github.com/codenvy/saas/issues/158
- [x] Can input not allowed characters for CAPS - https://github.com/codenvy/saas/issues/150
- [x] Billing summary on Get more RAM widget and invoice result differ - https://github.com/codenvy/saas/issues/154
- [x] Conflict with permissions  https://github.com/codenvy/codenvy/issues/1709
- [x] Impossible to create workspace into a team - https://github.com/codenvy/codenvy/issues/1609
- [x] Unable to start workspace when RAM Cap is unlimited https://github.com/codenvy/codenvy/issues/1720
- [x] Should be able to remove CAP or set it to 0 https://github.com/codenvy/codenvy/issues/1710
- [x] User cannot remove itself from own team https://github.com/codenvy/codenvy/issues/1608
- [x] Workspace of team member is not visible for team admin/owner https://github.com/codenvy/codenvy/issues/1672
- [x] Impossible to create a workspace when team has not configured properly https://github.com/codenvy/codenvy/issues/1639
- [x] IDE error message is displayed when click on billing invoices - https://github.com/codenvy/codenvy/issues/1605
- [x] User should be redirected somewhere if it is trying to rich nonexisted team - https://github.com/codenvy/codenvy/issues/1606
- [x] A button which does nothing on creation workspace page -https://github.com/codenvy/codenvy/issues/1607
- [x] Wrong subtitle displayed on deleting billing information - https://github.com/codenvy/codenvy/issues/1616
- [x] Unexpected behavior while setting Workspace Cap and Running Workspace Cap values - https://github.com/codenvy/codenvy/issues/1622
- [x] Double scrollbar in billing invoices - https://github.com/codenvy/codenvy/issues/1629
- [x] Add scrollbar to teams list in left navbar - https://github.com/codenvy/codenvy/issues/1642
- [x] Set credit card number input max value - https://github.com/codenvy/codenvy/issues/1649
- [x] Show summary section on Get more RAM popup - https://github.com/codenvy/codenvy/issues/1659
- [x] Fix Add/edit team member popup state and behavior - https://github.com/codenvy/codenvy/issues/1679

**To be fixed after shipping - P2**
- [x] Nonexistent account/team is not handled https://github.com/codenvy/codenvy/issues/1693
- [x] Tabs flickering in team's details and billing - https://github.com/codenvy/codenvy/issues/1756
- [x] User should be clearly notified if user id is the same with team name - https://github.com/codenvy/codenvy/issues/1604

- [x] sample
- [x] sample

**Postponed**
- [ ] sample bug

## Enhancements
**To be fixed before shipping**
- [x] Improve Developers section https://github.com/codenvy/codenvy/issues/1715
- [x] Should be possible to use '-' into team's name - https://github.com/codenvy/codenvy/issues/1610

**To be fixed after shipping**
- [ ] Add list of teams on dashboard page - https://github.com/codenvy/saas/issues/175
- [ ] Simplify number of fields required for billing information - 
- [ ] Data lost when switching to another tab in Billing screen -https://github.com/codenvy/saas/issues/151
- [x] Improve renaming a team https://github.com/codenvy/codenvy/issues/1719
- [ ] Team selector does not scale when many teams exist - https://github.com/codenvy/codenvy/issues/1686

## Known Functional Gaps
In this section, we list all the features and capabilities that are identified by all testers as _missing_, which could significantly impact users. 
**To be fixed before shipping**
- [x] Default workspace sharing scenario - see comment in (https://github.com/codenvy/codenvy/issues/1672#issuecomment-278357229)
- [x] Change resource distribution to setting resource CAPs https://github.com/codenvy/codenvy/issues/1729 
- [x] Team owner has to be able to see members of the team https://github.com/codenvy/codenvy/issues/1730
- [x] Email notifications on team changes - https://github.com/codenvy/codenvy/issues/1759
- [x] All the resources defined in package template should be charged properly https://github.com/codenvy/codenvy/issues/1787
- [x] send mail about invoice status - https://github.com/codenvy/customer-saas/issues/125
- [x] Team name should be unique inside personal organization, not system wide - https://github.com/codenvy/codenvy/issues/1674
- [x] Process the list of credit card errors from braintree https://github.com/codenvy/codenvy/issues/1727
- [x] Improve Workspace RAM Cap description - https://github.com/codenvy/codenvy/issues/1623
- [x] Display workspace idle timeout in workspace's details - https://github.com/codenvy/codenvy/issues/1633
- [x] Add mention about workspace idle timeout in "Get More RAM" popup - https://github.com/codenvy/codenvy/issues/1634
- [x] Add ability to contact support to get help on account - https://github.com/codenvy/codenvy/issues/1635

**Postponed**
- [x] Ability for a team member to leave the team - https://github.com/codenvy/saas/issues/168
- [x] Ability to invite users which are not already Codenvy users - https://github.com/codenvy/saas/issues/161
- [x] Don't add unregistered user to a team - https://github.com/codenvy/codenvy/issues/1670
- [x] User does not have the ability to downgrade his subscription(s)
- [ ] User does not have the ability to cancel his subscription(s)
- [x] Show suggestion when adding users - https://github.com/codenvy/codenvy/issues/1624
- [x] Notify user on team changes - https://github.com/codenvy/codenvy/issues/1644
- [x] Show notifications to team member on team changes - https://github.com/codenvy/codenvy/issues/1643 
- [x] Display workspace's member for workspaces list in team

## Reports / Feedbacks / Found bugs
In this section we keep a list of opened bugs/feedbacks that we have not yet verified and classified. 
- [x] Handle Enter keypress for name field to instant team creation - https://github.com/codenvy/codenvy/issues/1613
- [x] Set workspace RAM limit on workspace creation/details based on team's CAP -https://github.com/codenvy/codenvy/issues/1640
- [x] Let user to set resource limits on team creation - https://github.com/codenvy/codenvy/issues/1647
- [x] Disable workspace creation if there are no available resources - https://github.com/codenvy/codenvy/issues/1648
- [ ] Wrong alignment in team workspaces table - https://github.com/codenvy/codenvy/issues/1671
- [x] Strange behavior when user is not authorized https://github.com/codenvy/codenvy/issues/1688
- [x] A admin is not able to select other members workspaces for deleting them -https://github.com/codenvy/codenvy/issues/1866
- [x] The countries list is deprecated - https://github.com/codenvy/codenvy/issues/1867
- [x] Unexpected browser alert pop up after switching between ws. from nav bar https://github.com/codenvy/codenvy/issues/1871

**Comment by bmicklea** [comment]
@slemeur I'll take the website items.

**Comment by riuvshin** [comment]
@slemeur @TylerJewell do we need 5.2.0 milestone here? 5.2.0 release next week.

**Comment by slemeur** [comment]
Closing as step 1 has been handled. The remaining tasks are enhancements/improvements
