### ISSUE TITLE
5.1.0 Milestone Overview

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#1666]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che [milestone 5.1.0](https://github.com/eclipse/che/issues/3972).

This release includes:
- Dockerized Codenvy: Install a private Codenvy anywhere Docker runs.
- Fair Source 3 (Free) User License: Built-in, non-expiring, 3 user license.
- New CLI: Offline installation, simple configuration, and data backup.
- LDAP Integration: Synchronization and authentication for LDAP / AD.
- BitBucket Server Integrations: Connect to JIRA, Jenkins and automate pull requests with BitBucket repos.
- Consolidate Databases: Because a single database is easier to manage.
- Auditing Capabilities: Track workspace usage and license compliance.
- Built-in Documentation: {your-codenvy-url}/docs to get help.

This release includes improvements from Eclipse Che 5, the world’s most popular open source cloud IDE and developer workspace server:
- Docker Compose Runtimes: Dev workspaces with multiple containers.
- Workspace Snapshots: Auto-image and auto-restore workspace state
- Workspace Agents: Inject developer services into any workspaces.
- Docker Exec Agent: Replaces docker exec with Golang REST server for executing commands.
- Stack Editor: Create stacks with your runtime, or edit and test any of our 30+ default stacks.
- Language Server Protocol: Add intellisense for any language.
- New Debuggers: Added new Node.JS and Zend PHP debuggers.
- SSH: Automatic key generation across all machines in a workspace.
- Desktop Sync: Synchronize workspaces with your local IDE.
- More Responsive: Filesystem watchers optimize file operations and browser updates.
- Split & Resize: Terminals and editors can be split and sized to your exacting requirements.
- PHP: Auto-complete, definitions, debugging and more.
- Bitnami Stacks: Certified workspace stacks for popular languages and frameworks.
- Chedir: Reproducible cloud workspaces from your local repo.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.
## Schedule

This release will be a development release available on GitHub only.

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started
#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub
## Target Milestone Issues

The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "_Stretch_" before the item.
#### Issues

- [x] My SQL stack does not start kind/bug severity/P1  #1524  
- [x] NPE when creating workspace when there is already running ones kind/bug #1506  
- [x] Click on element in a project explorer jumps to the top of a tree kind/bug kind/question severity/P2 #1488  
- [x] Scripts that build Codenvy CLI and other images fail on Ubuntu 16.04 kind/bug #1485  
- [x] Audit license returned misleading info about expired and removed license actions kind/bug #1437  
- [x] Delete docs folder kind/docs severity/P1 #1425  
- [x] Instance started via CLI on Fedora linux fails on curl() command kind/bug #1374  
- [x] Add zookeeper configuration to runbook details kind/docs #1369  
- [x] Error occurred while deleting snapshot kind/bug  #1334  
- [x] Null Pointer in JpaWorkerDao kind/bug severity/blocker   #1321  
- [x] Null Pointer in WorkspaceRuntimes kind/bug severity/P1   #1320  
- [x] Navigate To File case sensitive? kind/enhancement  #1038  
- [x] Snapshot on workspace stop behavior kind/enhancement   #937   
- [x] Investigate if requests to dockerhub are made when using localy built workspace images kind/bug   #880   
- Unable to run Docker Codenvy, "please rerun CLI" [\#1538](https://github.com/codenvy/codenvy/issues/1538)
- CLI for creating organizations and users [\#1537](https://github.com/codenvy/codenvy/issues/1537)
- Authentication for Preview [\#1535](https://github.com/codenvy/codenvy/issues/1535)
- Running Codenvy in Docker: Workspace Agent Not Responding [\#1495](https://github.com/codenvy/codenvy/issues/1495)
- Update Codenvy to Use Renamed Che Docker Images [\#930](https://github.com/codenvy/codenvy/issues/930)
- workspaces does not start from snapshots on codenvy.io [\#1544](https://github.com/codenvy/codenvy/issues/1544)
- My SQL stack does not start [\#1524](https://github.com/codenvy/codenvy/issues/1524)
- NPE when creating workspace when there is already running ones [\#1506](https://github.com/codenvy/codenvy/issues/1506)
- Click on element in a project explorer jumps to the top of a tree [\#1488](https://github.com/codenvy/codenvy/issues/1488)
- Scripts that build Codenvy CLI and other images fail on Ubuntu 16.04 [\#1485](https://github.com/codenvy/codenvy/issues/1485)
- Audit license returned misleading info about expired and removed license actions [\#1437](https://github.com/codenvy/codenvy/issues/1437)
- Delete docs folder [\#1425](https://github.com/codenvy/codenvy/issues/1425)
- Instance started via CLI on Fedora linux fails on curl\(\) command [\#1374](https://github.com/codenvy/codenvy/issues/1374)
- Add zookeeper configuration to runbook details [\#1369](https://github.com/codenvy/codenvy/issues/1369)
- Error occurred while deleting snapshot [\#1334](https://github.com/codenvy/codenvy/issues/1334)
- Null Pointer in JpaWorkerDao [\#1321](https://github.com/codenvy/codenvy/issues/1321)
- Null Pointer in WorkspaceRuntimes [\#1320](https://github.com/codenvy/codenvy/issues/1320)
- Navigate To File case sensitive? [\#1038](https://github.com/codenvy/codenvy/issues/1038)
- Snapshot on workspace stop behavior [\#937](https://github.com/codenvy/codenvy/issues/937)
- Investigate if requests to dockerhub are made when using localy built workspace images [\#880](https://github.com/codenvy/codenvy/issues/880)
- RELEASE: set tags for release [\#1545](https://github.com/codenvy/codenvy/pull/1545) ([riuvshin](https://github.com/riuvshin))
- Update pom.xml [\#1539](https://github.com/codenvy/codenvy/pull/1539) ([JamesDrummond](https://github.com/JamesDrummond))
- Remove docs folder [\#1536](https://github.com/codenvy/codenvy/pull/1536) ([JamesDrummond](https://github.com/JamesDrummond))
- Allow to cancel workspace start request [\#1534](https://github.com/codenvy/codenvy/pull/1534) ([evoevodin](https://github.com/evoevodin))
- Reduce image size by having single docker image layer when adding tomcat [\#1533](https://github.com/codenvy/codenvy/pull/1533) ([skabashnyuk](https://github.com/skabashnyuk))
- Allow to update users while linking [\#1532](https://github.com/codenvy/codenvy/pull/1532) ([evoevodin](https://github.com/evoevodin))
- add 5.0.1 version [\#1527](https://github.com/codenvy/codenvy/pull/1527) ([riuvshin](https://github.com/riuvshin))
- CODENVY-1506 Rework workspace manager methods to optionally return runtime info [\#1523](https://github.com/codenvy/codenvy/pull/1523) ([mkuznyetsov](https://github.com/mkuznyetsov))
- \[cli\] Fix indent for JMX so \[AVAILABLE\] tag is aligned with previous lines [\#1519](https://github.com/codenvy/codenvy/pull/1519) ([benoitf](https://github.com/benoitf))
- SAAS-101 : Allow cli inheritance without dockerfiles manifests [\#1516](https://github.com/codenvy/codenvy/pull/1516) ([benoitf](https://github.com/benoitf))
- CODENVY-1403: remove sync agents from existing WSs [\#1514](https://github.com/codenvy/codenvy/pull/1514) ([garagatyi](https://github.com/garagatyi))
- add possibility to configure logback host / port [\#1513](https://github.com/codenvy/codenvy/pull/1513) ([riuvshin](https://github.com/riuvshin))
- CODENVY-1150: change classes according to changes in CHE [\#1512](https://github.com/codenvy/codenvy/pull/1512) ([garagatyi](https://github.com/garagatyi))
- Fix build after merging of out-of-sync PR [\#1497](https://github.com/codenvy/codenvy/pull/1497) ([garagatyi](https://github.com/garagatyi))
- Fix sh issue \(was working only with bash\) [\#1494](https://github.com/codenvy/codenvy/pull/1494) ([benoitf](https://github.com/benoitf))
- Fix misleading info about expired/removed system license actions in audit log [\#1453](https://github.com/codenvy/codenvy/pull/1453) ([dmytro-ndp](https://github.com/dmytro-ndp))
- CODENVY-1149: Refactor workspace infrastructure provisioning. [\#1452](https://github.com/codenvy/codenvy/pull/1452) ([garagatyi](https://github.com/garagatyi))
- Fix Codenvy according changes in Che [\#1444](https://github.com/codenvy/codenvy/pull/1444) ([garagatyi](https://github.com/garagatyi))
- Adapt HostedDockerInstance constructor & tests [\#1441](https://github.com/codenvy/codenvy/pull/1441) ([evoevodin](https://github.com/evoevodin))
- CODENVY-1321 Add checking instance id to avoid NPE [\#1427](https://github.com/codenvy/codenvy/pull/1427) ([sleshchenko](https://github.com/sleshchenko))
- Add manually publishing cascade events in implementation of DAOs instead of using EntityListeners [\#1338](https://github.com/codenvy/codenvy/pull/1338) ([sleshchenko](https://github.com/sleshchenko))
