### ISSUE TITLE
Housekeeping around system license checking modules (Performance impact)

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1738]
Licenses checking made in not an optimal way: 
- Code is too monolithic. It introduces a lot of transitive dependencies in multiple places.
- Code is slow. For each http request code making one more to check license. It's very slow. 
- [ ] Allow to have dependency on codenvy-hosted-sso-client without need to depend on codenvy-hosted-machine-authentication https://github.com/codenvy/codenvy/issues/1737
- [x] Split codenvy-hosted-api-system-license module https://github.com/codenvy/codenvy/issues/1733
- [x] Do not make additional http request on each license check in SystemLicenseLoginFilter https://github.com/codenvy/codenvy/issues/1739
- [x] Move classes related to permissions checking to shared modules https://github.com/codenvy/codenvy/issues/1740
- [x] Review DB indexes and queries in SystemLicenseActionImpl https://github.com/codenvy/codenvy/issues/1741
 - [x] Refactor reference between license_action and license_action_attributes tables https://github.com/codenvy/codenvy/issues/1742
