### ISSUE TITLE
Restore ws-master state after inappropriate shutdown

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#1761]
Right now we have a couple of assumption
- all workspaces will be stopped during ws-master shutdown
- all projects are backuped during ws-master shutdown
- we are not restoring state of workspace during ws-master start.

In some cases when ws-master was terminated in not a proper way (JVM crash, os crash) it's possible that user may lost some part of his data that wasn't synced.

The goal of this task is to be able to recover ws-master state from DB or from state of docker containers.

- [ ] Serialize machine required fields as docker container labels https://github.com/eclipse/che/issues/4104
- [ ] Add ability to lookup running machine instances ·https://github.com/eclipse/che/issues/4105
- [ ] Recover workspace runtimes on workspace master start  https://github.com/eclipse/che/issues/4106

**Comment by skabashnyuk** [comment]
Will be fixed by https://github.com/eclipse/che/issues/5097
