### ISSUE TITLE
5.11.0 Milestone Overview 

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#2194]
## Milestone Overview
- Stability, bugs, performance issues, and archetypes for custom development.
- Continue Improvement on Teams.
- NOTE: This release includes changes from Eclipse Che [milestone 5.1.0]().

## Schedule

This release will be a marketed release.

For more information about our development process please see our [development process](https://github.com/eclipse/che/wiki/Development-Process) page.

#### Code complete milestone
- [ ] Code complete
- [ ] Smoke tests started
#### Release candidate created milestone
- [ ] Release candidate created
- [ ] Test cycles started
- [ ] Docs reviewed
#### GitHub release complete (QA verified) milestone
- [ ] Release complete
- [ ] Release notes updated
- [ ] Release information updated on GitHub

#### Target Milestone Pull Requests(TBD)
