### ISSUE TITLE
EPL Codenvy on-prem / remove licenses

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#2350]
- [x] Remove the fair source license check in the CLI during installation https://github.com/codenvy/codenvy/issues/2351 @riuvshin
- [x] Remove the fair source license check in the site during first login https://github.com/codenvy/codenvy/issues/2352 @vkuznyetsov 
- [x] Remove all elements of license enforcement from the server - Codenvy binary will be unrestricted for total seats, total ram, total servers. @tolusha 
- [x] Remove any license key input from the UD. @ashumilova  
- [x] Remove any restrictions that prevent team / group / scale capabilities from the UD. @ashumilova 
- [x] docs clean up https://github.com/codenvy/docs/issues/131 @bmicklea or @slemeur

**Comment by riuvshin** [comment]
@bmicklea @slemeur hey guys we need remove license stuff before end of current sprint we all are almost ready but we need help on docs. We have to be ready to close this today.

**Comment by bmicklea** [comment]
I'm on PTO today but I'll try and get to it later this afternoon

**Comment by riuvshin** [comment]
@benoitf Anatoly already proposed PR we just need review.
