### ISSUE TITLE
Provide Codenvy on-prem customers with migration path to Che on OpenShift

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#2517]
Codenvy on-prem customers are currently in a holding pattern waiting for Che on OpenShift (OCP, OSD and MiniShift) to provide the bulk of their existing functionality. They need this urgently as it will take them several weeks or months to thoroughly test and plan this migration.

### Minimum requirements for Che on OpenShift

- [ ] Instructions for deploying Che on OCP, OSD and Minishift.
- [ ] Multi-user capabilities are provided via KeyCloak (which provides oAuth and LDAP/AD auth mechanisms).
- [ ] Organizations page is included in the user dashboard.

### Acceptable limitations

- [ ] Resources cannot be limited from within the Che configuration as they could be with Codenvy, instead users will limit resources via OpenShift quotas.
- [ ] JIRA, VSTS and Jenkins integrations will not work with Che. Integrations can be created using Factories or customers can wait to use OpenShift.io once it is available.
- [ ] Codenvy audit service is not available, OpenShift audit logs can be used to track workspace creation and removal. License auditing is no longer necessary as Che is FOSS.

### Notes
Documentation for monitoring Che is a nice-to-have as there are a number of monitoring solutions that can be used to track Che and OpenShift. Similarly SSH will work differently as OpenShift has built-in methods for establishing a secure remote connection to a pod.

**Comment by bmicklea** [comment]
@slemeur please add any details I've missed to this issue.

**Comment by eivantsov** [comment]
@bmicklea my comments:

Organizations can have certain restrictions configured in che.env:

1. https://github.com/eclipse/che/blob/che6/dockerfiles/init/manifests/che.env#L593
2. https://github.com/eclipse/che/blob/che6/dockerfiles/init/manifests/che.env#L600
3. https://github.com/eclipse/che/blob/che6/dockerfiles/init/manifests/che.env#L606

Without multi tenancy, OpenShift quotas will affect just an account where master and all of the workspace pods run. Let's call it an admin account. So, applying quotas isn't the right way to set caps in this case. It is possible to prevent users from over consumption of resources through:

```
#CHE_LIMITS_USER_WORKSPACES_COUNT
#CHE_LIMITS_USER_WORKSPACES_RUN_COUNT
#CHE_LIMITS_USER_WORKSPACES_RAM
```
There are several scenarios possible like making it impossible to create personal workspaces - only though orgs while it is possible to set caps on orgs as well.

SSH isn't the only limitation. There are other limitations, including but not limited to permissions to files and folders for an arbitrary user (can be configured by OpenShift admin), sudo commands in general (can be configured by OpenShift admin), no Dockerfile recipe support  (and not yet dockerImage).

**Comment by bmicklea** [comment]
Thanks @eivantsov as we discussed please create an issue outlining the limitations and we can discuss which are acceptable for an initial version and which will need to be addressed (somehow) before release.

**Comment by slemeur** [comment]
Linking to Che epic https://github.com/eclipse/che/issues/7321

**Comment by hkolvenbach** [comment]
another issue i currently foresee for our migration of https://slx.cloud:
how is user data migrated (e.g. user accounts into keycloak, existing workspaces to openshift)? is there a feasible way for that?
