### ISSUE TITLE
A user should be able to delete his account (with all associated resources)

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#386]
We should enable users to entirely delete themselves from the system. This means deletion of such entities as user and all associated workspaces.

- [x] Create list of all entries that connected to user #387 
- [x] Create a service that will delete a user from marketo #388
- [x] Make sure "Delete this account" Button actually deletes this account #382 
- [x] Create a page to be displayed after user is deleted #389
- [x] Investigate strategies for cascade entities removing https://github.com/eclipse/che/issues/1803
