### ISSUE TITLE
Database consolidation - consolidating LDAP, Mongo, Postgres into common repository

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#391]
Continuation of https://github.com/eclipse/che/issues/1790 for Codenvy
- [x] FactoryDao implementation on JPA #392 
- [x] PreferenceDao implementation on JPA #393 
- [x] WorkerDao implementation on jpa #394 
- [x] Create JPA based CommonPermissionsStorage #395
- [x] Integrate JPA components/tools with Codenvy infrastructure #396
- [ ] Support PostgreSQL DB when perform backup/restore of Codenvy onprem #465 
- [x] Support PostgreSQL DB when change admin password of Codenvy onprem by Installation Manager #466 
- [x] Bypass usage of LDAP when getting number of Codenvy on-prem users in Installation Manager https://github.com/codenvy/codenvy/issues/584
- [x] Rework permissions mechanism for stacks and recipes https://github.com/codenvy/codenvy/issues/505
- [x] Remove ldap and mongo from puppet configuration # https://github.com/codenvy/codenvy/issues/578
- [x] JPA support of AdminUserService.getAll method https://github.com/codenvy/codenvy/issues/586
- [x] Adapt new permission mechanism to ACL wildcard https://github.com/codenvy/codenvy/issues/666

All the existing data should be migrated to the new storage.

For each MongoDB based storage, consider using driver directly for fetching _ALL_ the existing entity _IDENTIFIERS_ (because DAOs don't support such functionality) and then use MongoDB based DAOs for fetching entities and JPA based DAOs for storing data. 

For  LDAP based storages(Profile, User) use _AdminUserDao_ for getting all the users, 
and then reuse Jpa based implementations for storing them. 

In the way described above the migration itself shouldn't be painful at all, as existing storages are responsible for objects fetching and storing.

Please note that the order of migration is important.

- [x] Workspace data migration tool from MongoDB to PostgreSQL #475
- [x] SSH data migration tool from MongoDB to PostgreSQL #474
- [x] Snapshot data migration tool from Mongo to PostgreSQL #473
- [x] Stack data migration tool from Mongo to PostgreSQL #472
- [x] Recipe data migration tool from Mongo to PostgreSQL #471 
- [x] User preferences migration tool from Mongo to PostgreSQL  #470
- [x] User and profile data migration tool from LDAP to PostgreSQL #469
- [x] Factory migration tool from MongoDB to PostgreSQL  #468 
- [x] Permissions storage migration tool from Mongo to PostgreSQL #467 
- [x] Cascading removal of the stack and recipe permissions. https://github.com/codenvy/codenvy/issues/645

**Comment by skabashnyuk** [comment]
- [ ] Support PostgreSQL DB when perform backup/restore of Codenvy onprem #465
removed from scope of this issue
