### ISSUE TITLE
Create migration tool to migrate from LDAP/MongoDB to PostgreSQL

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#397]
All the existing data should be migrated to the new storage.

For each MongoDB based storage, consider using driver directly for fetching _ALL_ the existing entity _IDENTIFIERS_ (because DAOs don't support such functionality) and then use MongoDB based DAOs for fetching entities and JPA based DAOs for storing data. 

For  LDAP based storages(Profile, User) use _AdminUserDao_ for getting all the users, 
and then reuse Jpa based implementations for storing them. 

In the way described above the migration itself shouldn't be painful at all, as existing storages are responsible for objects fetching and storing.

Please note that the order of migration is important.

- [ ] Workspace data migration tool from MongoDB to PostgreSQL #475
- [ ] SSH data migration tool from MongoDB to PostgreSQL #474
- [ ] Snapshot data migration tool from Mongo to PostgreSQL #473
- [ ] Stack data migration tool from Mongo to PostgreSQL #472
- [ ] Recipe data migration tool from Mongo to PostgreSQL #471 
- [ ] User preferences migration tool from Mongo to PostgreSQL  #470
- [ ] User and profile data migration tool from LDAP to PostgreSQL #469
- [ ] Factory migration tool from MongoDB to PostgreSQL  #468 
- [ ] Permissions storage migration tool from Mongo to PostgreSQL #467

**Comment by skabashnyuk** [comment]
Close as duplicate Database consolidation - #391
