### ISSUE TITLE
Integration with customers ldap

### ISSUE THREAD

**Issue by skabashnyuk** [codenvy/codenvy#398]
In onprem installation customers usually have their own ldap based user  databases.
And they want:
- Provide only read-only access
- Be able to define subset of user who can access to codenvy
- Use same username - password database
- Do not double copy sensitive information like passwords

- [x] Study how to integrate with customers ldap #399
- [x] Implement Ldap Synchronizer for Users & Profiles  #400 
- [x] Authentication using external ldap  https://github.com/codenvy/codenvy/issues/793 
- [x] Describe different type of Ldap authentication (AD, Direct, Anonymous, Authenticated) https://github.com/codenvy/codenvy/issues/812
- [x] Describe and test SASL configuration of LDAP connection https://github.com/codenvy/codenvy/issues/813
- [x] Describe Ldap connection pool configuration https://github.com/codenvy/codenvy/issues/814
- [x] Describe and test ssl configuration of ldap connection https://github.com/codenvy/codenvy/issues/815
