### ISSUE TITLE
System resource management and production readiness

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#406]
This epic is related to all the work we have to do in order to make resource management resistant to unplanned limitations.

- [x] Prevent workspace starting if the system achieved resources limit https://github.com/codenvy/codenvy/issues/408
- [x] Limit Machine logs queue heap memory consumption https://github.com/codenvy/codenvy/issues/457
- [x] Create 'resource reached error' table in dasboard https://github.com/codenvy/codenvy/issues/502
