### ISSUE TITLE
Account and resources management 

### ISSUE THREAD

**Issue by vkuznyetsov** [codenvy/codenvy#409]
Accounts for resources management.
https://wiki.codenvycorp.com/display/PSR/Codenvy+4+Account+for+resources+management
It should be implement in some steps:

At first it is need to implement model with accounts, organizations, resources, licences which will allow to control resources usage by users.

Proposed to have next model https://github.com/sleshchenko/codenvy/pull/6/files
Then it is need to implement DAOs for it and minimal set of rest services for ability to start work on UI.
Implement checking of resources limits of workspace starting and machine adding to started workspace

DoD:

**_Organization management:_**

- [x] create, delete, update organization : https://github.com/codenvy/codenvy/issues/552

**_Members management:_**

- [x] add, remove member : https://github.com/codenvy/codenvy/issues/552
- [x] set, remove members permission : https://github.com/codenvy/codenvy/issues/552

**_Workspaces management:_**

- [x] create, remove workspaces thich belong to account (user or organization) https://github.com/codenvy/codenvy/issues/419
- [x] fetch workspaces by namespace (account name to wit user or organization name) https://github.com/codenvy/codenvy/issues/419

_**Resource management:**_

- [x] get license that defines resources of account https://github.com/codenvy/codenvy/issues/410
- [x] get list of resources which are available for usage, used https://github.com/codenvy/codenvy/issues/410
- [x] don't start workspace if there is no enough number of resources https://github.com/codenvy/codenvy/issues/410

**Bugfixes**
- [x] Deny users to create organization with name that is url incompatible or reserved: codenvy/codenvy#674
- [x] Rework members of organizations to fix build: codenvy/codenvy#673
- [x] Personal account was reworked from inheritance to delegating: codenvy/codenvy#672

**_UI Epic:_** https://github.com/codenvy/codenvy/issues/548

**Comment by vkuznyetsov** [comment]
depends on [(https://github.com/codenvy/codenvy/issues/391)]
