### ISSUE TITLE
Show Codenvy is production grade

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#412]
This is umbrella issue for things we need to do to achieve 2.2 item from Q3 plan.
- [x] How to diagnose failures of installation dependending upon the stage of installation.
we will provide a tool for collecting information for troubleshooting instead of manuals this way it will be much easier for customer and we will have all information we need by 1 request. #413
- [ ] How do you setup your operations environment to ensure that Codenvy never crashes at large scale usage :) #414 
- [ ] Create set of CI jobs to trigger in case of problems with SAAS when no any Admin available to handle that. #433
