### ISSUE TITLE
move to puppet 4.x

### ISSUE THREAD

**Issue by riuvshin** [codenvy/codenvy#434]
**This is not  part of Q3 goals. Because we don't know how hard will be to move completely on puppet 4.5.x**

Currently we are using puppet **3.8.x** but latest version is **4.5.x**. We was not able to start working on that because The foreman which we are using to monitor our puppet infrastructure was not supported puppet 4 and now in version **1.12.0** they added support of new puppet. Puppet 4.x dramatically changed a lot even it's own packages. 

Main goal of this epic is a bug fixes which will make puppetmaster much more stable in case how we using it. In puppet 3.8.x when you distribute large file like we do for our tomcat zips puppet perform check md5 algorithm to figure out should be file updated or not. md5 check is a very good for small configuration  files but for large files like our tomcat zips ~200mb it is very CPU expensive operation. It means that in a large scale our puppet master which is situated on API node may affect codenvy performance. In puppet 4.x that issue was fixed by adding possibility to choose file checksum strategy.
https://tickets.puppetlabs.com/browse/PUP-1208

Also puppet 4.x have a various improvements and fixes which is nice to have.

TODO list:
- [x] upgrade the foreman instance to 1.12.x
- [x] prepare base box for vagrant we are using for dev.box with puppet agent to 4.5.x
- [x] make default dev box using puppet 4.5.x to see how it works
- [ ] test puppet 4.5.x in master - agent mode (dev box is masterless)
- [ ] update puppet to 4.5.x on codenvy  test environments like nightly4 and acceptances
- [ ] prepare IM to be able to work with puppet 4.5.x
- [ ] develop migration procedure for onprems from puppet 3.8.x to 4.5.x

**Comment by riuvshin** [comment]
We don;t need this anymore.
