### ISSUE TITLE
Remove beta designation on hosted C4 systems

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#436]
For beta.codenvy.com:
- [ ] Remove security text on account creation page.
- [ ] Change domain from beta.codenvy.com to c4.codenvy.com
- [ ] Perform migration of internal database for any URLs that contain beta.codenvy.com to c4.*
- [ ] Add client redirect rule for beta.* to redirect to c4.*

The text to remove - all of this:
```
IMPORTANT
Codenvy next-generation is in beta. 
Do not import private projects, data or keys. 
This beta system has a 10 minute workspace idle timeout.
```

**Comment by vkuznyetsov** [comment]
Issue moved to saas project
