### ISSUE TITLE
Milestone Summary 4.6.0

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#478]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che [milestone 4.6.0](https://github.com/eclipse/che/issues/1870).

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be an Eclipse-signed and marketed release  (...or...This release will be an unsigned development release available on GitHub only).
**Target Release Dates**
- Code complete milestone: **target July 29**
- GitHub release complete (QA verified) milestone: **target August 2**
- Release shipped milestone: **target August 4**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

#### Release shipped milestone
- [x] Release blog live on codenvy.com
- [x] Marketing email / social notifications

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Epics and Issues
- [x] Investigate exception 'Machine with name ws-machine already exists' [#411](https://github.com/codenvy/codenvy/issues/411)

#### Bugs
- [x] On beta in logs [ERROR] [m.b.WorkspaceFsBackupScheduler 84] - Machine machine???? is not found [#454](https://github.com/codenvy/codenvy/issues/454)
- [x] Vagrant installer uses wrong proxy settings. [#440](https://github.com/codenvy/codenvy/issues/440)
- [x] Unable to create user by Admin Dashbord [#435](https://github.com/codenvy/codenvy/issues/435)
- [x] Sourcegraph factory examples from getting-started page works wrong [#430](https://github.com/codenvy/codenvy/issues/430)
- [x] Marketo interceptors doesn't send data to the Marketo [#427](https://github.com/codenvy/codenvy/issues/427)
- [x] Bitbucket oAuth is broken [#426](https://github.com/codenvy/codenvy/issues/426)
- [x] Missing pull request panel [#458](https://github.com/codenvy/codenvy/issues/458)
- [x] Cloning a VSTS repo feature does not work [#431](https://github.com/codenvy/codenvy/issues/431)
- [x] Methods "updateAttributesById" and "updateAttributes" in the ProfileService clean up user lastName in some case of partial update [#451](https://github.com/codenvy/codenvy/issues/451)
- [x] VSTS projects does cloning failed [#449](https://github.com/codenvy/codenvy/issues/449)
- [x] Change default dns http://codenvy to any dns which contain dot symbol [#407](https://github.com/codenvy/codenvy/issues/407)
- [x] Backup subs-system removes projects of workspace in some cases [#488](https://github.com/codenvy/codenvy/issues/488)

**Comment by bmicklea** [comment]
updated to remove che milestone items

**Comment by JamesDrummond** [comment]
This release has been delayed due to issues with our CI system. We will be updating the release as soon as the issues are fixed.
