### ISSUE TITLE
Add support of multiple AWS accounts/ECR registries in docker client

### ISSUE THREAD

**Issue by garagatyi** [codenvy/codenvy#524]
#521 provides possibility to use single AWS ECR. We need to add possibility to configure multiple ECR in multiple AWS accounts.
Related to #444 

Issues in epic:
- [ ] Add ability to support specific docker registries: https://github.com/eclipse/che/issues/2273
- [ ] Add ability to save workspace snapshots in AWS ECR : https://github.com/codenvy/codenvy/issues/515
- [ ] Add ability to remove workspace snapshots from AWS ECR: https://github.com/codenvy/codenvy/issues/632
- [ ]  Add support in server side of AWS user credentials for ECR configured in dashboard: https://github.com/codenvy/codenvy/issues/660
- [ ] Add form for adding AWS user credentials for ECR in the Codenvy dashboard: https://github.com/codenvy/codenvy/issues/642
- [ ] Add ability to configure registry for snapshots for each workspace: https://github.com/codenvy/codenvy/issues/663
- [ ] Add registry for snapshots option in workspace settings: https://github.com/codenvy/codenvy/issues/662

**Comment by bmicklea** [comment]
Please investigate how we would support the following use case:

If the user selects an external registry (including AWS ECR) for their images then...

**On a per-workspace basis:**
- The user can set the account, region, registry and keys to use for storing images.
- When the workspace is first successfully created a snapshot is taken and stored in the registry as the "original"
- When a later workspace snapshot is taken it will be added as "latest" and replace any previous "latest" that was already in the registry.
- On workspace startup the user is asked whether to load from snapshot (original or latest) or re-create from recipe.

**Comment by gazarenkov** [comment]
Our API does supports only "latest" workspace snapshot, I see no point in "original", it is the same as original image/recipe, why spending resources (it might be quite big image).

What is the point of creation per-user/per-ws storage? 
So far it looks like overkill to me, just adds complexity to API.

**Comment by bmicklea** [comment]
Agreed that the original snapshot isn't necessary and will only take up storage (which could be significant over time).

@mmorhun - would this make more sense:
**on a per user basis**
1. Set the AWS ECR credentials: account, region and keys

**on a per workspace basis**
1. Set the AWS registry to use (it would have to be accessible with the credentials set for the user.
2. When a workspace snapshot is taken it will be added as "latest" and replace any previous "latest" that was already in the registry.
3. On workspace startup the user is asked whether to load from snapshot (the default) or re-create from recipe.

**Comment by mmorhun** [comment]
@bmicklea 
>  Set the AWS registry to use (it would have to be accessible with the credentials set for the user.

It is not clear to me. 
In case of workspace creation, registry will be set by user in a recipe. So, setting a registry as an option has sense only for snapshotting.
Now we have Codenvy system property which says, which registry we should use for snapshots (for all users, for all workspaces). You said, that it should be configurable per workspace. But what should we do, if this parameter is not configured for a workspace? Show an error? Use registry from Codenvy system property? ... Please, provide more details.

**Comment by bmicklea** [comment]
Allowing the user to set the registry in the recipe is fine, as long as it works with AWS ECR.

**Comment by mmorhun** [comment]
> Allowing the user to set the registry in the recipe is fine, as long as it works with AWS ECR. That would be the normal way to do it.

@bmicklea could you please clarify. When a user create a workspace, he can use one of the ready-to-go images or create workspace from custom image. For now, any user can specify in a workspace recipe a registry from which an custom image for this new workspace will be pulled. It doesn't depends on a registry (AWS ECR, dockerhub, local registry - no matter) it is just common way to do it. If a user specified private registry, he have to set credentials for that registry before.
In case of snapshotting we should know which docker registry we should use. As I said, now we have Codenvy system property which store this value. In case of per workspace (or per user) configuration it should be saved in workspace (or user) preferences. But
>  what should we do, if this parameter is not configured for a workspace? Show an error? Use registry from Codenvy system property? ... Please, provide more details.

**Comment by bmicklea** [comment]
> what should we do, if this parameter is not configured for a workspace? Show an error? Use registry from Codenvy system property? ... Please, provide more details.

If the user hasn't provided credentials for the registry that's listed in the recipe we should show an error in the UD: "Workspace cannot be created because it uses an image from a private registry at <registry address>. Add your credentials for this registry in <location>."

If the user hasn't provided a parameter indicating where the snapshot should be saved we should use default registry.

**Comment by mmorhun** [comment]
> If the user hasn't provided credentials for the registry that's listed in the recipe

then build will fail, if it secured.
Also we do not know, is given permissions right. Moreover, may be we needn't permissions for that repo at all (we don't know is given registry secured, so we cannot show that error message).

> If the user hasn't provided a parameter indicating where the snapshot should be saved we should use default registry.

Thank you, It is what I wanted to know.

Ok, I am going to implement following requirements:
**on a per user basis**
1. Set the AWS ECR credentials: account, region and keys
**on a per workspace basis**
1. Set the AWS registry to use **for snapshots**(it would have to be accessible with the credentials set for the user).
2. When a workspace snapshot is taken it will be added as "latest" and replace any previous "latest" that was already in the registry.
3. On workspace startup the user is asked whether to load from snapshot (the default) or re-create from recipe.

@bmicklea if you have any remarks, please let me know.

**Comment by vkuznyetsov** [comment]
This issue also includes:
- [ ] https://github.com/codenvy/codenvy/issues/515
- [ ] https://github.com/codenvy/codenvy/issues/632

**Comment by mmorhun** [comment]
@bmicklea I have one more question. For now we store each snapshot in separate repository. It means, that if out workspace consists of two machines then we'll create two repositories (for each machine). Is it ok?

**Comment by garagatyi** [comment]
And if user have 10 workspaces with 2 machines in each workspace than we will create 20 repositories. 
We can use single repository instead and push snapshots with different tags. WDYT?

**Comment by garagatyi** [comment]
Why not use configuration of a registry per-user instead of per-workspace?
This will simplify UX and decrease time needed for implementation. 
@bmicklea can you explain the use-cases that requires per-workspace registry configuration?

**Comment by gazarenkov** [comment]
Why do we need per-user or per-workspace registry configuration at all?
The point is to make it possible using other than AWS docker registry instead of dockerhub on system (on-prem istallation) level IMO.
I could not see the opposite in initial task definition and it sounds completely reasonable.

**Comment by bmicklea** [comment]
@gazarenkov and @garagatyi - let's do per-user. Per-install isn't good enough because some of our customers have multiple registries that they use.

**Comment by gazarenkov** [comment]
We support particular backend for info (DB), particular backend for project storage (FS), for user database (LDAP or RDB). All are conceptually pluggable, each installation has own but we never considered that as individual per-user storage (it would look strange). Why we should change the rules for Snapshots (which the same managed by our API)? 
And BTW formally we have no obligations about format and form we store it, it is our internal way how we store and restore it, user should not care about it, it is infrastructure's job.

**Comment by bmicklea** [comment]
I'm not sure I understand. Imagine that you and I both had ECR keys and registries but they were different. I can't use yours and you can't use mine. It has to be per-user at that point. They can't have a single registry for the whole product because they have >5 different business units.

**Comment by gazarenkov** [comment]
I am not sure I understand you.
Maybe we are talking about different things.
What I mean is that there should be one and only place to store Snapshots.
We can have a plugins to many of them. 
But if it is configured per-installation that it uses for example AWS ECR registry everyone uses it and is not able to configure for example DockerHub to himself individually.

**Comment by bmicklea** [comment]
In speaking with the customer about the challenges we are having they agreed:

**Must Have**
- Allow Codenvy Admin to setup a set of available private registries (including account, region and keys) that can be accessed by users.
- Users can pull images for their workspaces from any of these pre-configured registries
- Snapshots are stored in a single location (can even be locally)

*Nice to Have**
- Users can select the AWS ECR registry where snapshots of the workspace should be stored

**Comment by gazarenkov** [comment]
Yes, there can be several private registry implementations can be configured in the system (when they implement it) - the matter of authentication mechanism implementation (I have not talked about it in fact). 
And, yes,  "Snapshots are stored in a single location (can even be locally)"  - that's what I was talking about.

**Comment by bmicklea** [comment]
Great, then this is ready to be developed, correct?

@garagatyi please update the epic definition to reflect this scope.

**Comment by garagatyi** [comment]
@bmicklea As far as I understand current expectation is to have auth configs of registries (account, region and keys) configured per-system, not per-user. Am I correct?

**Comment by bmicklea** [comment]
Yes, per system, but with the ability for the user to choose from those when they do an image pull. Snapshots will be centrally stored in a single location.

**Comment by garagatyi** [comment]
User can't choose storage of image on pull. Pulling includes image reference that includes url of registry. So we can not use another registry for pulling.

**Comment by bmicklea** [comment]
Yes, I understand - the use case is that the admin of the system has keys to registry where the desired image is stored. The admin adds that registry and keys to the Codenvy system then a developer can pull and image from that registry and Codenvy will use the admin-added keys to do it so that the user themselves doesn't need to know the registry keys.

**Comment by garagatyi** [comment]
yes

**Comment by bmicklea** [comment]
@garagatyi this epic now reflects the complete solution - can you provide a rough estimate of time to implement?  I ask because an interim step could remove the following tasks:

https://github.com/codenvy/codenvy/issues/515
https://github.com/codenvy/codenvy/issues/632
https://github.com/codenvy/codenvy/issues/642

And possibly these if they are only needed if we allow configuration through the user dashboard (it would be acceptable to configure AWS ECR through configuration files in the interim):
https://github.com/codenvy/codenvy/issues/660
https://github.com/codenvy/codenvy/issues/662

**Comment by garagatyi** [comment]
For all the cases with per-system configuration we need:
#515 
#632 

Issues for case with per-user/workspace configurations:
#642 
#660 
#662 
#663 

Since we decided that we can start from simple implementation we can close second set of issues. These sets also lack issue for configuring several registries per-system. It is also not implemented yet.

**Comment by bmicklea** [comment]
@garagatyi I think this epic captures the interim state accurately - (https://github.com/codenvy/codenvy/issues/727). However, we do need to support multiple AWS ECR registries per install. Is there an issue created for that already?

**Comment by garagatyi** [comment]
#727 Covers usage AWS as a snapshot storage, but title describes another case. Snapshots use not only pulls, but also pushes. 

AFAIK we don't have an issue for support of keys for multiple registries. It is also needed for #727.

> I think this epic captures the interim state accurately - (#727) and it will be clearer to use 727 and close this epic as won't address.
If so, please close this epic and all issues from second list from my previous comment.

**Comment by bmicklea** [comment]
Replaced by #727
