### ISSUE TITLE
Codenvy Milestone 4.7.0

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#525]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che milestone 4.7.0 [#2029](https://github.com/eclipse/che/issues/2029).

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a published and marketed release.

**Target Release Dates**
- Code complete milestone: **target August 26**
- GitHub release complete (QA verified) milestone: **target August 30**
- Release shipped milestone: **target August 31**

#### Code complete milestone
- [x] Milestone issues complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

#### Release shipped milestone
- [x] Release blog live on codenvy.com
- [x] Marketing email / social notifications

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Epics and Issues
- [x] Share a workspace: User not found message when sharing a workspace: #509 
- [x] Add record '127.0.0.1 <new-hostname>' into /etc/hosts when changing Codenvy on-prem hostname: #464 
- [x] Support of AWS ECR dynamic passwords #453 

#### Bugs
- [x] Create a page to be displayed after user is deleted #389
- [x] Docker machine impl doesn't stop and remove containers if script that restores projects FS fails #447 
- [x] Update codenvy config and update of Codenvy version hung up on https://<hostname> address: #459 
- [x] Can't checkout git repo in version 4.5.1 #476 
- [x] Factories with open file action do not get into the workspace #507 
- [x] Installation manager doesn't store empty codenvy property #512 
- [x] Issue with snapshots #541 
- [x] Default admin name of zabbix is "Admin", not "admin". #547 
- [x] Wrong behavior while creating new account. #550 
- [x] netstat deprecated and not available on some centos 7 distributions. Replace with `ss`. #560 
- [x] Container not cleaned up if it failed to start #562 
- [x] NPE on some old accounts #564 
- [x] Integration tests of installation manager failed because of lack of RHEL subscription #575
