### ISSUE TITLE
Invite user with email address and factory URL

### ISSUE THREAD

**Issue by TylerJewell** [codenvy/codenvy#529]
The goal is to provide a single function that allows administrators to invite new users to a Codenvy Enterprise / Codenvy SaaS using an email address & a Factory.  The goal is to minimize the time that a DevOps professional has in inviting his team with a workspace that is tailored to their project.  

Pre-conditions:
1: Codenvy Enterprise or Codenvy SaaS.
2: User logged in with admin credentials (has permissions to create accounts).
3: Self-service user registration is true or false.

Workflow:
1: As an admin, want to invite a new user to the system linked to a Factory.

2: Admin inputs: email address & the name of a factory, which could be chosen through UX in our product, from an available list of factories already installed.

3: The email address will act as the user name. There will be different workflows for users that already have an email address vs. those that do not.

4: User has an email address workflow
4.1: We will send a "Try This Workspace" email. This would be the same contents that we send now any time we allow a user to share a workspace or factory over email.  If we do not have such an email in the product, we should create one.  It would have Subject: "Try This Codenvy Workspace".  Body: "You have been invited to try this Codenvy Factory, which generates a workspace in your account with a set of runtimes and projects."  Button: "Generate Workspace".  Button Link: "The factory selected by the admin when initiating the request.  When the user clicks on this Factory link, it would be any normal Factory flow, including the obligation to authenticate before they can complete it.

5: User does not have an email address workflow
5.1: Create an account with the email address as the user name.
5.2: Prepare a "Welcome to Codenvy" email to be sent to the user.  

Subject: "Your Codenvy Account".  
Body: "You have a new account with Codenvy `! Your admin has created a sample workspace for you to use. 
  User Name:  <emailaddress>
  Password:  <password-generated-by-system>
  Change Password: http://reset-password-link"

Button: "Create Your First Workspace"
Button Link: This would be a factory URL that was provided by the admin when he generated the invite / account. This would then be a normal factory flow, where the user must authenticate with his credentials first.

- [ ] Invite with Factory REST capability.  Adhere to the workflow above.
- [ ] UX: In admin view, allow admin to invite a user with an email address and a factory. The list of factories should include the nice names of Factories that are currently loaded in Codenvy.
- [ ] UX: If admin logged in, and browsing a Factory, add a new share ability that let's admin share that particular factory with someone by providing their email address.

**Comment by TylerJewell** [comment]
Replaced by team capabilities.
