### ISSUE TITLE
Account and resource management in dashboard

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#548]
This epic is handling the UI part of resource management.

- [ ] Organization management https://github.com/codenvy/codenvy/issues/544
- [ ] Member management in organization https://github.com/codenvy/codenvy/issues/545
- [ ] Display account resources info on dashboard page https://github.com/codenvy/codenvy/issues/543 
- [ ] Prevent starting WS if there are no free resources for user https://github.com/codenvy/codenvy/issues/549

**Comment by TylerJewell** [comment]
closed - to be reopened as a new epic in conjunction with the team capabilities
