### ISSUE TITLE
Move Codenvy License management staff to Codenvy API Server

### ISSUE THREAD

**Issue by dmytro-ndp** [codenvy/codenvy#599]
## Short Description of Problem
There is a method [com.codenvy.im.managers.LdapManager#getNumberOfUsers](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/LdapManager.java#L114-L114) in _Installation Manager_ which is used by [com.codenvy.im.service.LicenseService#isCodenvyUsageLegal](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-server-war/src/main/java/com/codenvy/im/service/LicenseService.java#L172-L172) to verify if Codenvy is being used legally according to Codenvy license.

To avoid requesting to _Codenvy User DB_ directly from _Installation Manager_, and taking in mind that Codenvy API service to get Codenvy on-prem user number can't be public, we ought to move all _Codenvy License management_ staff from the _Installation Manager Server_ to _Codenvy API Server_.

## Implementation Steps
- [x] Move [com.codenvy.im.license](https://github.com/codenvy/codenvy/tree/4.6.2/cdec/installation-manager-core/src/main/java/com/codenvy/im/license) to Codenvy API Server (it uses third-part library [License4J](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/pom.xml#L68):
```
        <dependency>
            <groupId>com.license4j</groupId>
            <artifactId>license4j-runtime-library</artifactId>
        </dependency>
```

- [x] Move license-related properties from *installation-manager.properties* file to the Codenvy API server /home/codenvy/codenvy-data/conf/license.properties:
1. [license-manager.public_key](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/src/main/resources/codenvy/installation-manager.properties#L27) as it; 
1. [installation-manager.storage_dir](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/src/main/resources/codenvy/installation-manager.properties#L22) - to property *license-manager.license-file=/home/codenvy/codenvy-data/license/license*
- [x] Move [com.codenvy.im.service.LicenseService](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-server-war/src/main/java/com/codenvy/im/service/LicenseService.java) to Codenvy API Server:
use http://codenvy.onprem/api/license address instead of http://codenvy.onprem/im/license
- [x] Fix [com.codenvy.im.managers.helper.NodeManagerHelper#validateLicense](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/helper/NodeManagerHelperCodenvy4Impl.java#L272-L272) to use Codenvy API server to check license.
- [x] Add migration script to extract license from the **/usr/local/codenvy/im/storage/config.properties** file and store it in the file */home/codenvy/codenvy-data/license/license*.
- [x] Create replacement of [com.codenvy.im.managers.StorageManager](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-core/src/main/java/com/codenvy/im/managers/StorageManager.java#L47): to store license text as it into the file defined by property *license-manager.license-file* and load license from it.
- [x] Ensure that installation manager integration tests (for example: [test-add-remove-codenvy-nodes-with-codenvy4](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-tests/src/main/resources/bin/codenvy4/test-add-remove-codenvy-nodes-with-codenvy4.sh)), don't fail, and next methods work properly:
- [storeCodenvyLicense](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-tests/src/main/resources/bin/lib.sh#L457)
- [addCodenvyLicenseConfiguration](https://github.com/codenvy/codenvy/blob/4.6.2/cdec/installation-manager-tests/src/main/resources/bin/lib.sh#L450)
- [x] Ensure **User Dashboard** uses http://codenvy.onprem/api/license address instead of http://codenvy.onprem/im/license
- [x] Work around **manageCodenvy** permission of Codenvy.
- [x] Support old Codenvy on-prem 4.x versions where LicenseService is absent in API Server when validate license before adding machine nodes. https://github.com/codenvy/codenvy/pull/719
