### ISSUE TITLE
Codenvy Milestone 5.0.0-M1

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#664]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M1](https://github.com/eclipse/che/issues/2267).

**Note the workspace model change will break any stacks.json that has been customized.** Before upgrading to 5.0 ensure you have backed up your customized stacks.json so that you can re-create it within the new model.

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Epics and Issues
- [x] Gitlab integration. #628 

## Migration Considerations
Before upgrading to 5.0 ensure you have backed up your customized stacks.json so that you can re-create it within the new model.

**Comment by JamesDrummond** [comment]
Updated delivery targets based on results from latest merge activities.
