### ISSUE TITLE
Dashboard configuration of AWS ECR

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#743]
#524 added the ability to configure a set of AWS ECR registries from the user dashboard.

Issues in epic:
- [ ]  Add support in server side of AWS user credentials for ECR configured in dashboard: https://github.com/codenvy/codenvy/issues/660
- [ ] Add form for adding AWS user credentials for ECR in the Codenvy dashboard: https://github.com/codenvy/codenvy/issues/642
- [ ] Add ability to configure registry for snapshots for each workspace: https://github.com/codenvy/codenvy/issues/663
- [ ] Add registry for snapshots option in workspace settings: https://github.com/codenvy/codenvy/issues/662

**Comment by garagatyi** [comment]
Not needed anymore.
