### ISSUE TITLE
5.0.0-M3 Milestone Plan 

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#780]
## Milestone Overview
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M3](https://github.com/eclipse/che/issues/2641).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M3 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1 to 5.0.0-M2 an then 5.0.0-M3.**

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Issues
- [x] Describe configuration changes #762 
- [x] Sharing permission is not working #836 
- [x] Dashboard: bottom left button doesn't open a drop-down list. #835 
- [x] Improve error message when creating a factory from a workspace without projects. 
- [x] Editor not displayed to create a factory from template #821  
- [x] Impossible to upload factory configuration file #820  
- [x] Add support for AWS ECRs configuration properties in puppet #789  
- [x] Enable support for multiple AWS ECR registries per install #742  
- [x] Incomprehensible behavior for creation a factory from dashboard #637  
- [x] Create 'resource reached error' table in dasboard #502 
- [x] Puppet config isn't updated properly in time of changing Codenvy hostname when there are machine nodes #456 
- [x] User preferences migration tool from Mongo to PostgreSQL #470 
- [x] Cascading removal of the stack and recipe permissions. kind/task team/platform #645  
- [x] Permissions storage migration tool from Mongo to PostgreSQL kind/task team/platform #467  
- [x] Factory migration tool from MongoDB to PostgreSQL kind/task team/platform #468  
- [x] User and profile data migration tool from LDAP to PostgreSQL kind/task team/platform #469  
- [x] Recipe data migration tool from Mongo to PostgreSQL kind/task team/platform #471  
- [x] Stack data migration tool from Mongo to PostgreSQL kind/task team/platform #472  
- [x] Snapshot data migration tool from Mongo to PostgreSQL kind/task team/platform #473  
- [x] SSH data migration tool from MongoDB to PostgreSQL kind/task team/platform #474  
- [x] Workspace data migration tool from MongoDB to PostgreSQL kind/task team/platform #475  
- [x] Adapt new permission mechanism to ACL wildcard kind/task team/platform #666  
- [x] JPA support of AdminUserService.getAll method kind/task team/platform #586  
- [x] Rework permissions mechanism for stacks and recipes kind/task team/platform #505  
- [x] Integrate JPA components/tools with Codenvy infrastructure kind/enhancement team/platform #396  
- [x] WorkerDao implementation on jpa kind/enhancement team/platform #394  
- [x] FactoryDao implementation on JPA kind/task team/platform #392  
- [x] Remove LDAP & Mongo DAO implementations kind/task team/platform #597  
- [x] Remove ldap and mongo from puppet configuration kind/task sprint/current-sprint team/production #578  
- [x] Factories aren't opening from dashboard kind/bug severity/blocker team/plugin #766  
- [x] Page with settings of factory is not openning on dashboard kind/bug severity/blocker team/plugin #767  
- [x] Dashboard bug fixes #771  
- [x] Dashboard doesn't check if usage of Codenvy on-prem is legal according to license termskind/bug team/plugin #621   
- [x] Re-implement IM CLI login command to use Codenyv 4.x on-prem instance as a remote by default kind/enhancement team/enterprise #667  
- [x] Add ability to configure registry for snapshots for each workspace kind/enhancementstatus/open-for-dev team/enterprise #663  
- [x] Bypass usage of LDAP when getting number of Codenvy on-prem users in Installation Managerkind/epic #584  
- [x] Create JPA based CommonPermissionsStorage kind/enhancement team/platform #395  
- [x] PreferenceDao implementation on JPA kind/task team/platform #393  

## Migration Considerations
In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M3 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1 to 5.0.0-M2 an then 5.0.0-M3.
