### ISSUE TITLE
Team Phase 1 : UI Basics for Team capabilities

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#796]
UI Basics: implement the very first screen for team capabilities:
- [x] Add Team section to navigation bar https://github.com/codenvy/codenvy/issues/797 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Remove the latest sentence in the description of Team https://github.com/codenvy/codenvy/issues/1039 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Improve styles in the left navbar for consistent "Add" experience https://github.com/codenvy/codenvy/issues/1040 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Remove redrawing in Team popups https://github.com/codenvy/codenvy/issues/1042 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Consistent popup styles in Team https://github.com/codenvy/codenvy/issues/1041 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Add "Settings" page on Team details https://github.com/codenvy/codenvy/issues/798 
- [x] Add "Developers" page on Team details https://github.com/codenvy/codenvy/issues/799 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Add "Team Workspaces" page on Team details https://github.com/codenvy/codenvy/issues/800 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Ability to create a workspace in a Team https://github.com/codenvy/codenvy/issues/801 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Filter workspaces by team on workspace list page https://github.com/codenvy/codenvy/issues/802  ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)
- [x] Ability to create new team https://github.com/codenvy/codenvy/issues/803 ![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif)

![checked-checkbox-16](https://cloud.githubusercontent.com/assets/1611939/20708923/ecc0cc20-b63a-11e6-870e-b481b8f0963f.gif) - items done in branch https://github.com/codenvy/codenvy/tree/Teams_1
