### ISSUE TITLE
Team Phase 1 : Billing with only RAM

### ISSUE THREAD

**Issue by ashumilova** [codenvy/codenvy#862]
The goal of the epic is to prepare billing part for the first phase of the Team capabilities. It handles only RAM limits (buying more RAM). This epic includes both API and UI part for team billing stuff.

- [ ] Study what we can reuse from 3.x billing model  https://github.com/codenvy/customer-saas/issues/57
- [ ] Subscription management API https://github.com/codenvy/codenvy/issues/859
- [ ] Payment management API https://github.com/codenvy/codenvy/issues/860
- [ ] Invoices management API https://github.com/codenvy/codenvy/issues/861
- [ ] Ability to show and handle billing information in dashboard https://github.com/codenvy/codenvy/issues/856
- [ ] UI for managing credit card https://github.com/codenvy/codenvy/issues/857
- [ ] Display user's invoices https://github.com/codenvy/codenvy/issues/858

**Comment by ashumilova** [comment]
Moved to https://github.com/codenvy/customer-saas/issues/63
