### ISSUE TITLE
5.0.0-M4 Milestone Plan

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#888]
## Milestone Overview
- Bug fixes and cleanup
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M4](https://github.com/eclipse/che/issues/2615).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M4 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1 or 5.0.0-M2 to 5.0.0-M4.**

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Issues
- [x] Inform admin about important changes in update command output after update of Codenvy on-prem **severity/blocker** #865  
- [x] Remove che-in-che stack from saas + on-prem offering **severity/blocker** #846  
- [x] NPE during start workspace from default environment #850  
- [x] Can not share workspace to another user #725  

## Migration Considerations
In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M4 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1 or 5.0.0-M2 to 5.0.0-M4.
