### ISSUE TITLE
5.0.0-M5 Milestone Plan

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#889]
## Milestone Overview
- Bug fixes and cleanup
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M5](https://github.com/eclipse/che/issues/2359).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M5 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1, 5.0.0-M2, or 5.0.0-M4 to 5.0.0-M5.**

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Issues
- [X] Can't load workspaces on nightly **(regression)** kind/bug severity/blocker #912   
- [X] Deleting of user removes all public recipes kind/bug severity/blocker #905   
- [X] Activity checker stops working after few hours kind/bug severity/blocker #899   
- [X] After consuming a factory by Direct URL the terminal does not work kind/bug severity/blockers #755   
- [X] Search recipes does not work correctly **(regression)** kind/bug #909   
- [X] Snapshot creation sometimes fails kind/bug #903   
- [X] Project type 'php' is not found (Bitnami Codeigniter stack) kind/bug #879   
- [X] Merge changes to support JIRA plugin improvements kind/task #873   
- [X] put nginx behind haproxy to eliminate requirement open 444 port kind/enhancement #869   
- [X] Login to Codenvy through IM ClI failed kind/bug #826   
- [X] Describe and test ssl configuration of ldap connection kind/task #815   
- [X] Describe Ldap connection pool configuration kind/task #814   
- [X] Describe different type of Ldap authentication (AD, Direct, Anonymous, Authenticated) kind/task #812   
- [X] Authentication using external ldap kind/task #793   
- [X] Workspace member sharing widget changes kind/bug #775   
- [X] Fix listed grammar errors in dashboard kind/bug #774   
- [X] System admin configuration in ldap syncronisation mode kind/task #732   
- [X] Can't create a factory from a workspace with SVN project kind/bug #687   
- [X] Investigate Codenvy JIRA plugin on JIRA 7.1.9 kind/bug #684   
- [X] Deny users to create organization with name that is url incompatible or reserved kind/task #674   
- [X] Rework members of organizations to fix build kind/bug #673   
- [X] Rework organizational account from inheritance to delegating kind/task #672   
- [X] Add ability to get list of organizations where certain user is a member kind/task #669   
- [X] Allow per user overrides for all resource limit configs kind/enhancement  #582   
- [X] Implement API for organizations kind/enhancement #552   
- [X] Ways to mount folder inside host machine to auxiliary machine? kind/enhancement #499   
- [X] Support PostgreSQL DB when perform backup/restore of Codenvy onprem kind/task #465   
- [X] Implement Account API kind/enhancement #419   
- [X] Implement Resources management API kind/enhancement #410   
- [X] Prevent workspace starting if the system achieved resources limit. kind/task #408   
- [X] Implement Ldap Synchronizer for Users & Profiles #400   
- [X] Study how to integrate with customers ldap kind/task #399   

## Migration Considerations
In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M5 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M1, 5.0.0-M2, or 5.0.0-M4 to 5.0.0-M5
