### ISSUE TITLE
Team Capabilities

### ISSUE THREAD

**Issue by slemeur** [codenvy/codenvy#916]
# Dedicated Epics
- [x] Team Phase 1 : UI Basics for Team capabilities https://github.com/codenvy/codenvy/issues/796
- [x] Team Phase 1 : Billing with only RAM https://github.com/codenvy/customer-saas/issues/63
- [x] Productization: https://github.com/codenvy/codenvy/issues/1549

# Goal
The goal of this document is to document the various user stories and requirements around Team capabilities in Codenvy and the onboarding sequence from Eclipse Che to Codenvy by creating teams. 
# Definitions

**Workspace Templates**
A workspace template is the association of a workspace configuration with a set of team settings (repositories, servers, databases...).
A workspace template provide a ready-to-work workspace and allow developers to be guided in order to do a proper setup.

**Runtime Stacks**
Runtime stack is is an environment configuration for a workspace defined by its runtime recipe.
(aka Stacks with 4.x)

**Project Samples**
Project samples are ready-to-go code samples and templates packaged with Che/Codenvy that can be imported into a workspace.
(aka Templates with 4.x)

**Team**
A group of developers who want to collaborate securely on a project managed by a “leader”.

**Account**
An object that holds resources and has billing attached with a single owner (with a single email as UID).
# Rules
- Every person who signs up is the owner of their account
- All accounts have an internal organization object which is called the personal team (labelled “personal”)
- The account is given 3 free seats (including theirs) and 3GB of RAM for free
  - The account owner can add seats and RAM at any time
- All workspaces are private and cannot be made public
- New workspaces can be created in the the “personal” team (default) or any other team the user is a member of
- New runtime stacks and project samples are always created in the “personal” team and can later be shared with any team that the user is a member of
- The owner can create a new team at any time:
  - Each team must name their new team (can’t be called “personal”)
  - The owner is referred to as the “leader” of the team
  - The team leader invites other developers to the team
  - The team leader can choose to share any of the custom runtime stacks, project samples and workspaces templates they’ve created with the team
- Everyone can:
  - Consume system runtime stacks
  - Consume system project samples
  - Create a workspace in teams that they are a member of (if they have the permission to)
  - Execute any factory URL published that they can click on
- Team admins can:
  - Create workspaces with access and resources shareable within the team (using permission system)
  - This is done by creating a workspace that lives in a team & inviting people to the team
  - Share workspace as workspace templates to the whole team
  - Share runtime stacks to a team
  - Share project samples to a team
  - Invite people to the team
- Team members (developers) can:
  - Access team workspaces
  - Use system runtime stacks & project samples to create workspaces in any team they are a member of, including their personal team
  - Use team runtime stacks & project samples to create workspaces in the team the stack / template is part of
  - Use workspace templates to create workspaces in the team the stack / template is part of
- Billing
  - A user can buy _seats_ or _RAM_
  - Free for all users:
    - 3GB RAM with idle timeout of 10minutes 
  - 3 seats
  - When a user is paying for at least 1GB RAM
    - workspaces are always on
  - user should be able to configure idle timeout for workspaces
# Flow1: Creating a Team for the Dashboard

Until the user is not part of any other team than his "personal" one, the user will have the following dashboard screen. 
![9 - dashboard no team](https://cloud.githubusercontent.com/assets/1636769/18705040/d08a704e-7fec-11e6-8ed3-ed40099f21fb.png)

There is a "Team" section in the left sidebar which allow the user to create a new team. 
![8 - team creation](https://cloud.githubusercontent.com/assets/1636769/18705056/eb70e9a6-7fec-11e6-91b1-345cbdc3e8b4.png)

The user is invited to provide a name to the new team and will be set as owner of the team. User can invite other developers to the team and select the workspace which will be shared as workspace templates. Similarly, user can share stacks (which are not the system one) to the team.

While creating the team, user can upgrade his account and book new seats.
_When credit card configured_
![8 - team creation cc already there](https://cloud.githubusercontent.com/assets/1636769/18705070/fef3c156-7fec-11e6-8dba-69dfef5dbea8.png)

_When credit card not configured_
![8 - team creation add cc](https://cloud.githubusercontent.com/assets/1636769/18705078/1067c9d2-7fed-11e6-885c-e43f81fe4e78.png)
# Flow2: Team details

_Team settings:_
![8 - team details - settings](https://cloud.githubusercontent.com/assets/1636769/18705106/342583b4-7fed-11e6-83ed-bf3e1e8d69c8.png)

A team leader will be able to require each developers of the team to configure certain settings. Those can be access to private repositories and servers, databases.

_Team developers:_
![8 - team details - developers](https://cloud.githubusercontent.com/assets/1636769/18475180/cd18698e-79c5-11e6-968e-a7a1ebe12c9b.png)

_Team workspace templates:_
![8 - team details - templates](https://cloud.githubusercontent.com/assets/1636769/18705184/75b15d30-7fed-11e6-8d33-217e744099f2.png)

_Add workspace templates:_
![8 - team details - add templates](https://cloud.githubusercontent.com/assets/1636769/18475356/6b194932-79c6-11e6-8713-6f572cac77b7.png)

_Team runtime stacks:_
![8 - team details - stacks](https://cloud.githubusercontent.com/assets/1636769/18705187/7db739e6-7fed-11e6-837a-7d68deed5561.png)

_Add runtime stacks:_
![8 - team details - add stack](https://cloud.githubusercontent.com/assets/1636769/18475404/92f31e42-79c6-11e6-85af-6224f54638f8.png)

_Team workspaces:_
![8 - team details - team workspaces](https://cloud.githubusercontent.com/assets/1636769/18475431/a6eb711a-79c6-11e6-93c5-b494f6591abf.png)
# Flow 3: Joining a Team

_Dashboard with invitations:_
![9 - dashboard team notifications](https://cloud.githubusercontent.com/assets/1636769/18705291/fa574a36-7fed-11e6-985f-4f14b964d675.png)

_Joining a team - Step 1:_
![9 - dashboard - join team - step1](https://cloud.githubusercontent.com/assets/1636769/18475592/4b549f2e-79c7-11e6-82b3-ad4d36da974c.png)

_Joining a team - Step 2:_
![9 - dashboard - join team - step2](https://cloud.githubusercontent.com/assets/1636769/18475598/51534f06-79c7-11e6-8617-90a5a9b7df74.png)
# Flow4: Setup a workspace from a workspace template

_Dashboard with invitations:_
![9 - dashboard team notifications](https://cloud.githubusercontent.com/assets/1636769/18705291/fa574a36-7fed-11e6-985f-4f14b964d675.png)
- Setup workspace from workspace template - Step1:*
  ![9 - dashboard - join workspace - step1](https://cloud.githubusercontent.com/assets/1636769/18706208/5c4df6e2-7ff1-11e6-898b-71ee4100ff44.png)
- Setup workspace from workspace template - Step2:*
  ![9 - dashboard - join workspace - step2](https://cloud.githubusercontent.com/assets/1636769/18706214/62459c08-7ff1-11e6-9e2d-b967d64abc94.png)
- Setup workspace from workspace template - Step3:*
  ![9 - dashboard - join workspace - step3](https://cloud.githubusercontent.com/assets/1636769/18706233/77f580f4-7ff1-11e6-889f-02718b8b1db3.png)
- Setup workspace from workspace template - Step4:*
  ![9 - dashboard - join workspace - step4](https://cloud.githubusercontent.com/assets/1636769/18706238/7c6ea64c-7ff1-11e6-960d-307cf7c3acb9.png)
# Flow5: Creating a workspace in a Team

_Create workspace flow:_
![create workspace in team](https://cloud.githubusercontent.com/assets/1636769/18706306/c5b5a526-7ff1-11e6-9d51-9160909d17c7.png)
# Flow6: Impact on workspace screens

_List of workspaces:_
![browse list of workspaces](https://cloud.githubusercontent.com/assets/1636769/18706323/d71d68f8-7ff1-11e6-8150-eb2d380265b0.png)
# Flow7: Billing screens

_Billing summary:_
![10 - billing - summary](https://cloud.githubusercontent.com/assets/1636769/18475999/c21f7b8c-79c8-11e6-874e-8b232bdfc5e7.png)

_Billing Info with CC:_
![10 - billing - billing info cc](https://cloud.githubusercontent.com/assets/1636769/18476031/d4925410-79c8-11e6-9773-3fc5e1e7ad6b.png)

_Billing Info without CC:_
![10 - billing - billing info](https://cloud.githubusercontent.com/assets/1636769/18476049/e2ff6cea-79c8-11e6-8789-bca1b4f4d2fe.png)

_Invoices:_
![10 - billing - invoices](https://cloud.githubusercontent.com/assets/1636769/18476063/eb8cf8dc-79c8-11e6-920a-97d84271b63b.png)

_Corner case: Removing CC while subscriptions are existing_
Either credit card is removed OR credit card fails at end of the month AND the account has more invites or more RAM.
The expected behavior is to let the user come down to 3 invites + 3GB RAM. 

**RAM**
- By default, we stop all workspaces.  Let user restart workspaces normally when they come back into the product and applying the new rule. 

**Invites**
- We freeze the account.  Any time the account owner login, we do not allow user to open workspaces until he has either added a valid CC OR has uninvited enough people to get to <=3.
- For team members, they will see the workspaces in the list, but when they will try to access a workspace, they will have an error message: "The subscription attached to the team workspace has expired. Please contact team.account.owner@."
