### ISSUE TITLE
Snapshot improvements

### ISSUE THREAD

**Issue by bmicklea** [codenvy/codenvy#940]
While our system can snapshot workspaces the usability of snapshotting makes this unclear for users.  This epic is to improve the behavior of snapshotting.

- [x] Blocker: Stop the workspace when a snapshot is executed #933 
- [x] UI does not accurately represent workspace snapshot state #931
- [x] Stopped IDE should provide clear state and options to the user #932
- [x] Clarify messages in UD for snapshotting #936
- [ ] Improve snapshotting policy. #937
