### ISSUE TITLE
5.0.0-M6 Milestone Plan

### ISSUE THREAD

**Issue by JamesDrummond** [codenvy/codenvy#947]
## Milestone Overview
- Bug fixes and cleanup
- NOTE: This release includes changes from Eclipse Che [milestone 5.0.0-M6](https://github.com/eclipse/che/issues/2740).

**In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M5 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M5 to 5.0.0-M6..**

For more information about our development process please see our [development process] (https://github.com/eclipse/che/wiki/Development-Process) page.

## Schedule
This release will be a development release available on GitHub only.

**Target Release Dates**
- Code complete milestone: **TBD**
- GitHub release complete (QA verified) milestone: **TBD**

#### Code complete milestone
- [x] Code complete
- [x] Smoke tests started

#### Release candidate created milestone
- [x] Release candidate created
- [x] Test cycles started
- [x] Docs reviewed

#### GitHub release complete (QA verified) milestone
- [x] Release complete
- [x] Release notes updated
- [x] Release information updated on GitHub

## Target Milestone Issues
The following issues are targeted for inclusion in the milestone. As issues are closed they are checked. Stretch goals are indicated with "*Stretch*" before the item.

#### Issues

- [X] Dashboard doesn't display nag message about the illegal usage of Codenvy on-prem kind/bug severity/blocker #1009  
- [X] It is difficult to login in Codenvy with username and password if it contains upper case symbol kind/bug #992   
- [X] Error of setting multi-line codenvy property by using Installation Manager kind/bug severity/blocker #982   
- [X] Error pushing to GitHub origin repo kind/question #968   
- [X] The editor is not updated after git checkout branch kind/bug #946   
- [X] Workspace run doesn't work properly in all cases kind/bug severity/blocker #935   
- [X] Stop the workspace when a snapshot is executed kind/bug severity/blocker #933   
- [X] UI does not accurately represent workspace snapshot state kind/bug #931   
- [X] Correctly handle absence of "eth0" for on-prem install kind/enhancement #922   
- [X] Sourcegraph sample from Che getting started page broken (regression) kind/bug #915   
- [X] After add a project Pull request panel is duplicated kind/bug #910   
- [X] After consuming a factory with a project the pull request plugin becomes broken kind/bug severity/blocker #908   
- [X] Cannot perform pull request from just created branch kind/bug severity/blocker #906   
- [X] Codenvy Installation manager backup fails on long file path in workspace kind/bug #689   
- [X] Auditing Codenvy kind/enhancement #581   
- [X] Wrong behavior after create pull request on 'Pull request' panel kind/bug severity/blocker #546   
- [X] Wrong display status 'Pull request updated' on the 'Pull Request' panel. kind/bug #518   
- [X] Wrong message in the 'Pull request' panel after create pull request kind/bug #514   

## Migration Considerations
In order to upgrade and migrate an existing Codenvy install to this version 5.0.0-M5 it must be upgraded from 4.7.2 to 5.0.0-M1. This version can ONLY be upgrade from 5.0.0-M5 to 5.0.0-M6.
